#!/bin/bash

WAIT_HOST="$1"
WAIT_PORT=${2:-80}
ROUNDS=${3:-30}
DELAY=${4:-1}

if [ "$(which nc)" == "" ]; then
    echo Missing nc
    echo This might help: apt-get install netcat
    exit 1
fi

if [ "$WAIT_HOST" == "" ]; then
    echo "wait-for-service host [port] [rounds] [deplay]"
    exit 1
fi

while ! nc -q 1 $WAIT_HOST $WAIT_PORT </dev/null; do
    sleep $DELAY
    echo  [$ROUNDS] $(date) Waiting for $WAIT_HOST:$WAIT_PORT
    if (( $ROUNDS == 1 )); then
        exit 1
    fi
    let ROUNDS-=1
done

echo  [$ROUNDS] $(date) $WAIT_HOST:$WAIT_PORT is available
